services:
  db:
    container_name: auth_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - app-network

  app:
    container_name: auth_service
    stdin_open: true
    platform: linux/x86_64
    tty: true
    build: .
    command: bash entrypoint.sh
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "${APP_PORT:-3100}:3000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    external: true

volumes:
  db_data:
  bundle_cache:
