# frozen_string_literal: true

default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USER") { "root" } %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") { "root" } %>
  host: <%= ENV.fetch("MYSQL_HOST") { "127.0.0.1" } %>

development:
  <<: *default
  database: auth_service_development

test:
  <<: *default
  database: auth_service_test

production:
  <<: *default
  database: auth_service_production
  username: <%= ENV['AUTH_DB_USERNAME'] %>
  password: <%= ENV['AUTH_DB_PASSWORD'] %>
