# frozen_string_literal: true

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV.fetch('DB_USER') { 'root' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'password123' } %>
  host: <%= ENV.fetch('DB_HOST') { 'db' } %>

development:
  <<: *default

test:
  <<: *default
  database: auth_service_test

production:
  <<: *default
  database: auth_service_production
  username: <%= ENV['AUTH_DB_USERNAME'] %>
  password: <%= ENV['AUTH_DB_PASSWORD'] %>
