# frozen_string_literal: true

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV.fetch('DB_USER') { 'root' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'root' } %>
  host: <%= ENV['CI_DB_HOST'] || ENV.fetch('DB_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('DB_PORT') { 3306 } %>

development:
  <<: *default
  database: auth_service_development

test:
  <<: *default
  database: auth_service_test

production:
  <<: *default
  database: auth_service_production
  username: <%= ENV['AUTH_DB_USERNAME'] %>
  password: <%= ENV['AUTH_DB_PASSWORD'] %>
